version: "3"

services:
  app:
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ec2-54-210-170-227.compute-1.amazonaws.com"

  reverse-proxy:
    image: traefik
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
